(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(pickup robot key1)
(noop human)
(down robot)
(noop human)
(pickup robot key2)
(noop human)
(right robot)
(right human)
(up robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(down robot)
(noop human)
(handover robot human key2)
(noop human)
(handover robot human key1)
(right human)
(noop robot)
(unlock human key1 door4)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(unlock human key2 door5)
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(pickup human gem4)
