(down human)
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(right human)
(down robot)
(right human)
(down robot)
(up human)
(pickup robot key1)
(pickup human key2)
(down robot)
(down human)
(unlock robot key1 door4)
(right human)
(noop robot)
(right human)
(noop robot)
(unlock human key2 door5)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(up human)
(noop robot)
(pickup human gem2)
