(down human)
(right robot)
(right human)
(right robot)
(right human)
(pickup robot key2)
(right human)
(left robot)
(right human)
(left robot)
(up human)
(down robot)
(noop human)
(handover robot human key2)
(unlock human key2 door2)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(down human)
(noop robot)
(pickup human gem3)
