(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(pickup robot key2)
(noop human)
(left robot)
(noop human)
(pickup robot key1)
(noop human)
(left robot)
(noop human)
(down robot)
(right human)
(unlock robot key2 door2)
(right human)
(down robot)
(noop human)
(down robot)
(noop human)
(unlock robot key1 door3)
(right human)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(pickup human gem2)
