(noop human)
(up robot)
(noop human)
(right robot)
(noop human)
(pickup robot key3)
(noop human)
(left robot)
(noop human)
(up robot)
(noop human)
(pickup robot key2)
(noop human)
(down robot)
(right human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(handover robot human key3)
(noop human)
(handover robot human key2)
(right human)
(noop robot)
(right human)
(noop robot)
(unlock human key3 door4)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(unlock human key2 door3)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(pickup human gem2)
