(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(pickup robot key2)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(handover robot human key2)
(unlock human key2 door1)
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(pickup human gem2)
