(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(pickup robot key2)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(up robot)
(noop human)
(up robot)
(right human)
(up robot)
(noop human)
(up robot)
(noop human)
(unlock robot key2 door2)
(right human)
(noop robot)
(right human)
(noop robot)
(unlock human key1 door3)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(up human)
(noop robot)
(pickup human gem2)