(noop human)
(up robot)
(noop human)
(right robot)
(noop human)
(pickup robot key5)
(noop human)
(left robot)
(noop human)
(up robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(down robot)
(noop human)
(pickup robot key4)
(noop human)
(up robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(handover robot human key4)
(unlock human key4 door3)
(handover robot human key5)
(right human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(up human)
(noop robot)
(unlock human key5 door1)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(pickup human gem1)
