(noop human)
(up robot)
(noop human)
(up robot)
(noop human)
(right robot)
(noop human)
(pickup robot key2)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(pickup robot key1)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(left robot)
(noop human)
(handover robot human key1)
(unlock human key1 door4)
(handover robot human key2)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(unlock human key2 door5)
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(pickup human gem3)
