(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(up robot)
(noop human)
(up robot)
(noop human)
(left robot)
(noop human)
(pickup robot key3)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(pickup robot key4)
(noop human)
(left robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(down robot)
(noop human)
(handover robot human key3)
(noop human)
(handover robot human key4)
(down human)
(noop robot)
(down human)
(noop robot)
(unlock human key3 door3)
(noop robot)
(down human)
(noop robot)
(unlock human key4 door4)
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(pickup human gem3)
