(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(up robot)
(noop human)
(up robot)
(noop human)
(left robot)
(noop human)
(pickup robot key5)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(pickup robot key6)
(noop human)
(left robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(down robot)
(noop human)
(handover robot human key5)
(noop human)
(handover robot human key6)
(right human)
(noop robot)
(unlock human key5 door1)
(noop robot)
(right human)
(noop robot)
(unlock human key6 door2)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(up human)
(noop robot)
(pickup human gem1)
