(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(pickup robot key2)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(pickup robot key3)
(noop human)
(down robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(handover robot human key2)
(unlock human key2 door4)
(handover robot human key3)
(right human)
(noop robot)
(right human)
(noop robot)
(unlock human key3 door5)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(pickup human gem4)
