(right human)
(right robot)
(right human)
(right robot)
(right human)
(right robot)
(noop human)
(up robot)
(noop human)
(pickup robot key3)
(right human)
(right robot)
(pickup human key1)
(up robot)
(right human)
(handover robot human key3)
(unlock human key3 door3)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(left human)
(noop robot)
(unlock human key1 door2)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(pickup human gem2)
