(right human)
(down robot)
(right human)
(down robot)
(right human)
(right robot)
(pickup human key3)
(right robot)
(right human)
(right robot)
(right human)
(pickup robot key5)
(down human)
(right robot)
(down human)
(right robot)
(down human)
(right robot)
(down human)
(noop robot)
(down human)
(handover robot human key5)
(unlock human key5 door3)
(noop robot)
(down human)
(noop robot)
(unlock human key3 door4)
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(pickup human gem4)
