(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(pickup robot key2)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(right robot)
(noop human)
(up robot)
(noop human)
(pickup robot key1)
(noop human)
(down robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(handover robot human key2)
(noop human)
(handover robot human key1)
(right human)
(noop robot)
(unlock human key2 door2)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(unlock human key1 door1)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(pickup human gem2)
