(right human)
(right robot)
(noop human)
(up robot)
(noop human)
(pickup robot key2)
(noop human)
(up robot)
(noop human)
(up robot)
(noop human)
(handover robot human key2)
(unlock human key2 door2)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(pickup human gem2)
