(move robot table1 cabinet4)
(move human table1 cabinet2)
(grab robot cutleryfork1 cabinet4)
(grab human plate1 cabinet2)
(grab robot cutleryfork2 cabinet4)
(grab human plate2 cabinet2)
(grab robot cutleryknife1 cabinet4)
(noop human)
(grab robot cutleryknife2 cabinet4)
