(move human table1 cabinet2)
(noop robot)
(grab human plate1 cabinet2)
(noop robot)
(move human cabinet2 fridge1)
(noop robot)
(grab human wine1 fridge1)
(noop robot)
(grab human cheese1 fridge1)
; Can you find 3 forks and some glasses?
