; Can you give me the red and the blue key?
(down human)
(down robot)
(down human)
(down robot)
(noop human)
(right robot)
(noop human)
(pickupr robot key2)
(noop human)
; 
(left robot)
(right human)
(left robot)
(noop human)
(pickupr robot key1)
(noop human)
; 
(right robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(left robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
(handover robot human key1)
(unlockh human key1 door4)
(handover robot human key2)
; 
(right human)
(noop robot)
(right human)
(noop robot)
(unlockh human key2 door5)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(pickuph human gem4)
