; Can you pass me a red and blue key?
(noop human)
(up robot)
(noop human)
(left robot)
(right human)
(pickupr robot key2)
(right human)
; 
(right robot)
(right human)
(up robot)
(right human)
(pickupr robot key1)
(pickuph human key3)
(down robot)
(left human)
(down robot)
(unlockh human key3 door3)
; 
(down robot)
(noop human)
(handover robot human key2)
(noop human)
(handover robot human key1)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
; 
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(unlockh human key2 door2)
(noop robot)
(up human)
(noop robot)
(up human)
; 
(noop robot)
(unlockh human key1 door1)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(up human)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(pickuph human gem1)
