; Can you pass me the blue key?
(noop human)
(noop robot)
(right human)
(up robot)
(right human)
(left robot)
(right human)
(pickupr robot key2)
; 
(right human)
(right robot)
(pickuph human key3)
(down robot)
(left human)
(noop robot)
(unlockh human key3 door3)
(down robot)
(noop human)
(handover robot human key2)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
; 
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(left human)
(noop robot)
(unlockh human key2 door4)
; 
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(pickuph human gem3)
