; Pass me the red and blue key.
(noop human)
(noop robot)
(right human)
(up robot)
(right human)
(left robot)
(right human)
(pickupr robot key2)
; 
(right human)
(right robot)
(pickuph human key3)
(up robot)
(left human)
(pickupr robot key1)
(unlockh human key3 door3)
(down robot)
(noop human)
(down robot)
(noop human)
(down robot)
(noop human)
; 
(handover robot human key1)
(noop human)
(handover robot human key2)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
; 
(noop robot)
(down human)
(noop robot)
(down human)
(noop robot)
(unlockh human key1 door5)
(noop robot)
; 
(right human)
(noop robot)
(right human)
(noop robot)
(unlockh human key2 door6)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
(pickuph human gem4)
