;Can you bring the plates?
(takeout human cutleryfork1 cabinet4)
(noop robot)
(takeout human cutleryfork2 cabinet4)
(noop robot)
(takeout human cutleryfork3 cabinet4)
(noop robot)
(takeout human cutleryknife1 cabinet4)
(noop robot)
(takeout human cutleryknife2 cabinet4)
(noop robot)
(takeout human cutleryknife3 cabinet4)
