;Could you fetch the rest of the knives and some plates?
(takeout human cutleryfork1 cabinet4)
(noop robot)
(takeout human cutleryfork2 cabinet4)
(noop robot)
(takeout human cutleryfork3 cabinet4)
(noop robot)
(takeout human cutleryfork4 cabinet4)
(noop robot)
(takeout human cutleryknife1 cabinet4)
(noop robot)
