(move human table1 cabinet2)
(noop robot)
(grab human plate1 cabinet2)
(noop robot)
(grab human plate2 cabinet2)
(noop robot)
(move human cabinet2 cabinet1)
(noop robot)
(grab human bowl1 cabinet1)
(noop robot)
(grab human bowl2 cabinet1)
(noop robot)
; We need some cutleries.
