(move human cabinet2)
(noop robot)
(grab human plate1 cabinet2)
(noop robot)
(grab human plate2 cabinet2)
(noop robot)
(grab human cutleryfork1 cabinet4)
(noop robot)
(grab human cutleryfork2 cabinet4)
(noop robot)
; Can you get the bowls?
