(move human table1 cabinet4)
(noop robot)
(grab human cutleryfork1 cabinet4)
(noop robot)
(grab human cutleryfork2 cabinet4)
(noop robot)
(grab human cutleryknife1 cabinet4)
(noop robot)
(grab human cutleryknife2 cabinet4)
; Can you get the plates?
