(move human table1 cabinet2)
(noop robot)
(grab human plate1 cabinet2)
(noop robot)
(grab human plate2 cabinet2)
(noop robot)
(grab human plate3 cabinet2)
(noop robot)
(move human cabinet2 cabinet4)
(noop robot)
(grab human cutleryfork1 cabinet4)
(noop robot)
(grab human cutleryfork2 cabinet4)
(noop robot)
(grab human cutleryknife2 cabinet4)
; Can you get more forks and knives?
