(move human table1 cabinet4)
(noop robot)
(grab human cutleryfork1 cabinet4)
(noop robot)
(grab human cutleryfork2 cabinet4)
(noop robot)
(grab human cutleryknife1 cabinet4)
(noop robot)
(move human cabinet4 table1)
; Could you fetch one more knife and some plates?
