(move robot table1 fridge1)
(noop human)
(grab robot wine1 fridge1)
(noop human)
(move robot fridge1 cabinet3)
(noop human)
(grab robot wineglass1 cabinet3)
(noop human)
(grab robot wineglass2 cabinet3)
(noop human)
(grab robot wineglass3 cabinet3)
