(move robot table1 cabinet3)
(noop human)
(grab robot wineglass1 cabinet3)
(noop human)
(grab robot wineglass2 cabinet3)
(noop human)
(grab robot wineglass3 cabinet3)
(noop human)
(move robot cabinet3 cabinet4)
(noop human)
(grab robot cutleryfork1 cabinet4)
(noop human)
(grab robot cutleryfork2 cabinet4)
(noop human)
(grab robot cutleryfork3 cabinet4)
