(move robot table1 cabinet4)
(move human table1 cabinet2)
(grab robot cutleryfork1 cabinet4)
(grab human plate1 cabinet2)
(grab robot cutleryfork2 cabinet4)
(grab human plate2 cabinet2)
(grab robot cutleryfork3 cabinet4)
(grab human plate3 cabinet2)
(grab robot cutleryknife1 cabinet4)
(noop human)
(grab robot cutleryknife2 cabinet4)
(noop human)
(grab robot cutleryknife3 cabinet4)
(move robot table1 cabinet3)
(move human table1 fridge1)
(grab robot wineglass1 cabinet3)
(grab human wine1 fridge1)
(grab robot wineglass2 cabinet3)
