(move robot table1 cabinet4)
(noop human)
(grab robot cutleryfork1 cabinet4)
(noop human)
(grab robot cutleryfork2 cabinet4)
(noop human)
(grab robot cutleryknife1 cabinet4)
(noop human)
(grab robot cutleryknife2 cabinet4)
