(move robot table1 cabinet2)
(noop human)
(grab robot plate3 cabinet2)
(noop human)
(grab robot plate4 cabinet2)
(noop human)
(move robot cabinet2 cabinet4)
(noop human)
(grab robot cutleryfork1 cabinet4)
(noop human)
(grab robot cutleryfork2 cabinet4)
(noop human)
(grab robot cutleryfork3 cabinet4)
(noop human)
(grab robot cutleryfork4 cabinet4)
(noop human)
(grab robot cutleryknife1 cabinet4)
(noop human)
(grab robot cutleryknife2 cabinet4)
(noop human)
(grab robot cutleryknife3 cabinet4)
(noop human)
(grab robot cutleryknife4 cabinet4)
