(noop human)
(move robot table1 cabinet4)
(noop human)
(grab robot cutleryknife1 cabinet4)
(noop human)
(grab robot cutleryknife2 cabinet4)
(noop human)
(move robot cabinet4 cabinet1)
(noop human)
(grab robot bowl1 cabinet1)
(noop human)
(grab robot bowl2 cabinet1)
