(noop human)
(move robot table1 cabinet4)
(noop human)
(grab robot cutleryknife2 cabinet4)
(noop human)
(grab robot cutleryknife3 cabinet4)
(noop human)
(grab robot cutleryknife4 cabinet4)
(noop human)
(move robot cabinet4 cabinet2)
(noop human)
(grab robot plate1 cabinet2)
(noop human)
(grab robot plate2 cabinet2)
(noop human)
(grab robot plate3 cabinet2)
(noop human)
(grab robot plate4 cabinet2)
