(move robot table1 cabinet2)
(move human table1 cabinet4)
(grab robot plate1 cabinet2)
(grab human cutleryfork1 cabinet4)
(grab robot plate2 cabinet2)
(grab human cutleryfork2 cabinet4)
(grab robot plate3 cabinet2)
(grab human cutleryfork3 cabinet4)
(noop robot)
(grab human cutleryknife1 cabinet4)
(noop robot)
(grab human cutleryknife2 cabinet4)
(noop robot)
(grab human cutleryknife3 cabinet4)
