(move robot table1 fridge1)
(noop human)
(grab robot cupcake1 fridge1)
(noop human)
(grab robot cupcake2 fridge1)
(noop human)
(grab robot cupcake3 fridge1)
(noop human)
(move robot fridge1 cabinet3)
(noop human)
(grab robot waterglass1 cabinet3)
(noop human)
(grab robot waterglass2 cabinet3)
(noop human)
(grab robot waterglass3 cabinet3)
