(define (problem doors-keys-gems-problem)
  (:domain doors-keys-gems)
  (:objects door1 door2 door3 door4 door5 door6 - door
            key1 key2 key3 key4 key5 key6 key7 - key
            gem1 gem2 gem3 gem4 - gem
            red yellow green blue - color
            robot - robot
            human - human)
  (:init (= (walls) (new-bit-matrix false 9 11))
         (= (agentcode human) 0)
         (= (agentcode robot) 1)
         (= (turn) 0)
         (= (walls) (set-index walls true 1 1))
         (= (walls) (set-index walls true 1 2))
         (= (walls) (set-index walls true 1 3))
         (= (walls) (set-index walls true 1 4))
         (= (walls) (set-index walls true 1 5))
         (= (walls) (set-index walls true 1 6))
         (= (walls) (set-index walls true 1 7))
         (= (walls) (set-index walls true 1 8))
         (= (walls) (set-index walls true 1 9))
         (= (walls) (set-index walls true 1 10))
         (= (walls) (set-index walls true 1 11))
         (= (xloc gem1) 1)
         (= (yloc gem1) 2)
         (= (xloc door1) 3)
         (= (yloc door1) 2)
         (iscolor door1 red)
         (locked door1)
         (= (walls) (set-index walls true 2 8))
         (= (walls) (set-index walls true 2 9))
         (= (walls) (set-index walls true 2 10))
         (= (walls) (set-index walls true 2 11))
         (= (walls) (set-index walls true 3 1))
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 3))
         (= (walls) (set-index walls true 3 4))
         (= (walls) (set-index walls true 3 5))
         (= (walls) (set-index walls true 3 6))
         (= (xloc door2) 7)
         (= (yloc door2) 3)
         (iscolor door2 red)
         (locked door2)
         (= (walls) (set-index walls true 3 8))
         (= (walls) (set-index walls true 3 9))
         (= (xloc key1) 10)
         (= (yloc key1) 3)
         (iscolor key1 red)
         (= (xloc key2) 11)
         (= (yloc key2) 3)
         (iscolor key2 red)
         (= (walls) (set-index walls true 4 1))
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 3))
         (= (walls) (set-index walls true 4 4))
         (= (walls) (set-index walls true 4 5))
         (= (walls) (set-index walls true 4 6))
         (= (walls) (set-index walls true 4 8))
         (= (walls) (set-index walls true 4 9))
         (= (xloc key3) 11)
         (= (yloc key3) 4)
         (iscolor key3 red)
         (= (xloc gem2) 1)
         (= (yloc gem2) 5)
         (= (xloc door3) 3)
         (= (yloc door3) 5)
         (iscolor door3 yellow)
         (locked door3)
         (= (xloc door4) 8)
         (= (yloc door4) 5)
         (iscolor door4 green)
         (locked door4)
         (= (xloc key4) 11)
         (= (yloc key4) 5)
         (iscolor key4 green)
         (= (walls) (set-index walls true 6 1))
         (= (walls) (set-index walls true 6 2))
         (= (walls) (set-index walls true 6 3))
         (= (walls) (set-index walls true 6 4))
         (= (walls) (set-index walls true 6 5))
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 8))
         (= (walls) (set-index walls true 6 9))
         (= (xloc key5) 11)
         (= (yloc key5) 6)
         (iscolor key5 yellow)
         (= (walls) (set-index walls true 7 1))
         (= (walls) (set-index walls true 7 2))
         (= (walls) (set-index walls true 7 3))
         (= (walls) (set-index walls true 7 4))
         (= (walls) (set-index walls true 7 5))
         (= (walls) (set-index walls true 7 6))
         (= (walls) (set-index walls true 7 8))
         (= (walls) (set-index walls true 7 9))
         (= (xloc key6) 10)
         (= (yloc key6) 7)
         (iscolor key6 blue)
         (= (xloc key7) 11)
         (= (yloc key7) 7)
         (iscolor key7 blue)
         (= (xloc gem3) 1)
         (= (yloc gem3) 8)
         (= (xloc door5) 3)
         (= (yloc door5) 8)
         (iscolor door5 blue)
         (locked door5)
         (= (xloc door6) 6)
         (= (yloc door6) 8)
         (iscolor door6 red)
         (locked door6)
         (= (walls) (set-index walls true 8 8))
         (= (walls) (set-index walls true 8 9))
         (= (walls) (set-index walls true 8 10))
         (= (walls) (set-index walls true 8 11))
         (= (walls) (set-index walls true 9 1))
         (= (walls) (set-index walls true 9 2))
         (= (walls) (set-index walls true 9 3))
         (= (walls) (set-index walls true 9 4))
         (= (walls) (set-index walls true 9 5))
         (= (walls) (set-index walls true 9 6))
         (= (xloc gem4) 7)
         (= (yloc gem4) 9)
         (= (walls) (set-index walls true 9 8))
         (= (walls) (set-index walls true 9 9))
         (= (walls) (set-index walls true 9 10))
         (= (walls) (set-index walls true 9 11))
         (= (xloc human) 5)
         (= (yloc human) 5)
         (= (xloc robot) 9)
         (= (yloc robot) 5))
  (:goal (has human gem4))
)