(define (problem doors-keys-gems-problem)
  (:domain doors-keys-gems)
  (:objects door1 door2 door3 door4 door5 door6 door7 door8 - door
            key1 key2 key3 key4 key5 key6 - key
            gem1 gem2 gem3 gem4 - gem
            blue red - color
            robot - robot
            human - human)
  (:init (= (walls) (new-bit-matrix false 10 9))
         (= (agentcode human) 0)
         (= (agentcode robot) 1)
         (= (turn) 0)
         (= (walls) (set-index walls true 1 1))
         (= (walls) (set-index walls true 1 2))
         (= (xloc key1) 3)
         (= (yloc key1) 1)
         (iscolor key1 red)
         (= (walls) (set-index walls true 1 4))
         (= (walls) (set-index walls true 1 5))
         (= (walls) (set-index walls true 1 6))
         (= (xloc key2) 7)
         (= (yloc key2) 1)
         (iscolor key2 red)
         (= (walls) (set-index walls true 1 8))
         (= (walls) (set-index walls true 1 9))
         (= (walls) (set-index walls true 2 1))
         (= (xloc key3) 2)
         (= (yloc key3) 2)
         (iscolor key3 red)
         (= (xloc key4) 4)
         (= (yloc key4) 2)
         (iscolor key4 red)
         (= (walls) (set-index walls true 2 5))
         (= (xloc key5) 6)
         (= (yloc key5) 2)
         (iscolor key5 blue)
         (= (xloc key6) 8)
         (= (yloc key6) 2)
         (iscolor key6 blue)
         (= (walls) (set-index walls true 2 9))
         (= (walls) (set-index walls true 3 1))
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 4))
         (= (walls) (set-index walls true 3 5))
         (= (walls) (set-index walls true 3 6))
         (= (walls) (set-index walls true 3 8))
         (= (walls) (set-index walls true 3 9))
         (= (walls) (set-index walls true 4 1))
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 8))
         (= (walls) (set-index walls true 4 9))
         (= (walls) (set-index walls true 5 1))
         (= (walls) (set-index walls true 5 2))
         (= (walls) (set-index walls true 5 3))
         (= (walls) (set-index walls true 5 4))
         (= (walls) (set-index walls true 5 6))
         (= (walls) (set-index walls true 5 7))
         (= (walls) (set-index walls true 5 8))
         (= (walls) (set-index walls true 5 9))
         (= (xloc gem1) 1)
         (= (yloc gem1) 6)
         (= (xloc door1) 2)
         (= (yloc door1) 6)
         (iscolor door1 blue)
         (locked door1)
         (= (xloc door2) 6)
         (= (yloc door2) 6)
         (iscolor door2 red)
         (locked door2)
         (= (xloc door3) 7)
         (= (yloc door3) 6)
         (iscolor door3 red)
         (locked door3)
         (= (xloc door4) 8)
         (= (yloc door4) 6)
         (iscolor door4 red)
         (locked door4)
         (= (xloc gem2) 9)
         (= (yloc gem2) 6)
         (= (walls) (set-index walls true 7 1))
         (= (walls) (set-index walls true 7 2))
         (= (walls) (set-index walls true 7 3))
         (= (walls) (set-index walls true 7 4))
         (= (walls) (set-index walls true 7 6))
         (= (walls) (set-index walls true 7 7))
         (= (walls) (set-index walls true 7 8))
         (= (walls) (set-index walls true 7 9))
         (= (walls) (set-index walls true 8 1))
         (= (walls) (set-index walls true 8 2))
         (= (walls) (set-index walls true 8 3))
         (= (walls) (set-index walls true 8 4))
         (= (walls) (set-index walls true 8 6))
         (= (walls) (set-index walls true 8 7))
         (= (walls) (set-index walls true 8 8))
         (= (walls) (set-index walls true 8 9))
         (= (walls) (set-index walls true 9 1))
         (= (walls) (set-index walls true 9 2))
         (= (walls) (set-index walls true 9 3))
         (= (walls) (set-index walls true 9 4))
         (= (walls) (set-index walls true 9 6))
         (= (walls) (set-index walls true 9 7))
         (= (walls) (set-index walls true 9 8))
         (= (walls) (set-index walls true 9 9))
         (= (xloc gem3) 1)
         (= (yloc gem3) 10)
         (= (xloc door5) 2)
         (= (yloc door5) 10)
         (iscolor door5 red)
         (locked door5)
         (= (xloc door6) 3)
         (= (yloc door6) 10)
         (iscolor door6 red)
         (locked door6)
         (= (xloc door7) 7)
         (= (yloc door7) 10)
         (iscolor door7 blue)
         (locked door7)
         (= (xloc door8) 8)
         (= (yloc door8) 10)
         (iscolor door8 blue)
         (locked door8)
         (= (xloc gem4) 9)
         (= (yloc gem4) 10)
         (= (xloc human) 5)
         (= (yloc human) 6)
         (= (xloc robot) 5)
         (= (yloc robot) 4))
  (:goal (has human gem4))
)