(define (problem doors-keys-gems-problem)
  (:domain doors-keys-gems)
  (:objects door1 - door
            key1 key2 - key
            gem1 gem2 gem3 gem4 - gem
            red - color
            robot - robot
            human - human)
  (:init (= (walls) (new-bit-matrix false 7 7))
         (= (agentcode human) 0)
         (= (agentcode robot) 1)
         (= (turn) 0)
         (= (xloc gem1) 1)
         (= (yloc gem1) 1)
         (= (walls) (set-index walls true 1 2))
         (= (walls) (set-index walls true 1 3))
         (= (walls) (set-index walls true 1 4))
         (= (walls) (set-index walls true 1 5))
         (= (walls) (set-index walls true 1 6))
         (= (walls) (set-index walls true 1 7))
         (= (xloc door1) 5)
         (= (yloc door1) 2)
         (iscolor door1 red)
         (locked door1)
         (= (xloc gem2) 7)
         (= (yloc gem2) 2)
         (= (walls) (set-index walls true 3 1))
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 3))
         (= (walls) (set-index walls true 3 5))
         (= (walls) (set-index walls true 3 6))
         (= (walls) (set-index walls true 3 7))
         (= (walls) (set-index walls true 4 1))
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 3))
         (= (xloc key1) 4)
         (= (yloc key1) 4)
         (iscolor key1 red)
         (= (walls) (set-index walls true 4 5))
         (= (walls) (set-index walls true 4 6))
         (= (walls) (set-index walls true 4 7))
         (= (xloc gem3) 1)
         (= (yloc gem3) 5)
         (= (xloc gem4) 7)
         (= (yloc gem4) 5)
         (= (walls) (set-index walls true 6 1))
         (= (walls) (set-index walls true 6 2))
         (= (walls) (set-index walls true 6 4))
         (= (walls) (set-index walls true 6 5))
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 7))
         (= (walls) (set-index walls true 7 1))
         (= (walls) (set-index walls true 7 2))
         (= (xloc key2) 5)
         (= (yloc key2) 7)
         (iscolor key2 red)
         (= (walls) (set-index walls true 7 6))
         (= (walls) (set-index walls true 7 7))
         (= (xloc human) 1)
         (= (yloc human) 2)
         (= (xloc robot) 3)
         (= (yloc robot) 6))
  (:goal (has human gem4))
)