(define (problem doors-keys-gems-problem)
  (:domain doors-keys-gems)
  (:objects door1 door2 door3 door4 door5 door6 - door
            key1 key2 key3 key4 - key
            gem1 gem2 gem3 gem4 - gem
            red blue - color
            robot - robot
            human - human)
  (:init (= (walls) (new-bit-matrix false 8 18))
         (= (agentcode human) 0)
         (= (agentcode robot) 1)
         (= (turn) 0)
         (= (walls) (set-index walls true 1 1))
         (= (walls) (set-index walls true 1 2))
         (= (walls) (set-index walls true 1 3))
         (= (walls) (set-index walls true 1 4))
         (= (xloc gem1) 5)
         (= (yloc gem1) 1)
         (= (walls) (set-index walls true 1 6))
         (= (walls) (set-index walls true 1 7))
         (= (walls) (set-index walls true 1 8))
         (= (walls) (set-index walls true 1 9))
         (= (walls) (set-index walls true 1 10))
         (= (walls) (set-index walls true 1 11))
         (= (walls) (set-index walls true 1 12))
         (= (walls) (set-index walls true 1 13))
         (= (walls) (set-index walls true 1 14))
         (= (xloc gem2) 15)
         (= (yloc gem2) 1)
         (= (walls) (set-index walls true 1 16))
         (= (walls) (set-index walls true 1 17))
         (= (walls) (set-index walls true 1 18))
         (= (walls) (set-index walls true 2 1))
         (= (walls) (set-index walls true 2 2))
         (= (walls) (set-index walls true 2 3))
         (= (walls) (set-index walls true 2 4))
         (= (xloc door1) 5)
         (= (yloc door1) 2)
         (iscolor door1 red)
         (locked door1)
         (= (walls) (set-index walls true 2 6))
         (= (walls) (set-index walls true 2 7))
         (= (walls) (set-index walls true 2 8))
         (= (walls) (set-index walls true 2 9))
         (= (walls) (set-index walls true 2 10))
         (= (walls) (set-index walls true 2 11))
         (= (walls) (set-index walls true 2 12))
         (= (walls) (set-index walls true 2 13))
         (= (walls) (set-index walls true 2 14))
         (= (xloc door2) 15)
         (= (yloc door2) 2)
         (iscolor door2 red)
         (locked door2)
         (= (walls) (set-index walls true 2 16))
         (= (walls) (set-index walls true 2 17))
         (= (walls) (set-index walls true 2 18))
         (= (walls) (set-index walls true 3 1))
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 3))
         (= (xloc key1) 8)
         (= (yloc key1) 3)
         (iscolor key1 red)
         (= (walls) (set-index walls true 3 9))
         (= (walls) (set-index walls true 3 10))
         (= (xloc key2) 15)
         (= (yloc key2) 3)
         (iscolor key2 red)
         (= (walls) (set-index walls true 3 16))
         (= (walls) (set-index walls true 3 17))
         (= (walls) (set-index walls true 3 18))
         (= (walls) (set-index walls true 4 1))
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 3))
         (= (walls) (set-index walls true 4 5))
         (= (walls) (set-index walls true 4 6))
         (= (walls) (set-index walls true 4 7))
         (= (walls) (set-index walls true 4 9))
         (= (walls) (set-index walls true 4 10))
         (= (walls) (set-index walls true 4 12))
         (= (walls) (set-index walls true 4 13))
         (= (walls) (set-index walls true 4 14))
         (= (walls) (set-index walls true 4 16))
         (= (walls) (set-index walls true 4 17))
         (= (walls) (set-index walls true 4 18))
         (= (xloc gem3) 1)
         (= (yloc gem3) 5)
         (= (xloc door3) 2)
         (= (yloc door3) 5)
         (iscolor door3 red)
         (locked door3)
         (= (xloc door4) 3)
         (= (yloc door4) 5)
         (iscolor door4 blue)
         (locked door4)
         (= (walls) (set-index walls true 5 5))
         (= (walls) (set-index walls true 5 6))
         (= (walls) (set-index walls true 5 7))
         (= (walls) (set-index walls true 5 12))
         (= (walls) (set-index walls true 5 13))
         (= (walls) (set-index walls true 5 14))
         (= (xloc door5) 16)
         (= (yloc door5) 5)
         (iscolor door5 red)
         (locked door5)
         (= (xloc door6) 17)
         (= (yloc door6) 5)
         (iscolor door6 blue)
         (locked door6)
         (= (xloc gem4) 18)
         (= (yloc gem4) 5)
         (= (walls) (set-index walls true 6 1))
         (= (walls) (set-index walls true 6 2))
         (= (walls) (set-index walls true 6 3))
         (= (walls) (set-index walls true 6 5))
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 7))
         (= (walls) (set-index walls true 6 9))
         (= (walls) (set-index walls true 6 10))
         (= (walls) (set-index walls true 6 12))
         (= (walls) (set-index walls true 6 13))
         (= (walls) (set-index walls true 6 14))
         (= (walls) (set-index walls true 6 16))
         (= (walls) (set-index walls true 6 17))
         (= (walls) (set-index walls true 6 18))
         (= (walls) (set-index walls true 7 1))
         (= (walls) (set-index walls true 7 2))
         (= (walls) (set-index walls true 7 3))
         (= (xloc key3) 5)
         (= (yloc key3) 7)
         (iscolor key3 blue)
         (= (walls) (set-index walls true 7 9))
         (= (walls) (set-index walls true 7 10))
         (= (xloc key4) 13)
         (= (yloc key4) 7)
         (iscolor key4 blue)
         (= (walls) (set-index walls true 7 16))
         (= (walls) (set-index walls true 7 17))
         (= (walls) (set-index walls true 7 18))
         (= (walls) (set-index walls true 8 1))
         (= (walls) (set-index walls true 8 2))
         (= (walls) (set-index walls true 8 3))
         (= (walls) (set-index walls true 8 4))
         (= (walls) (set-index walls true 8 5))
         (= (walls) (set-index walls true 8 6))
         (= (walls) (set-index walls true 8 7))
         (= (walls) (set-index walls true 8 8))
         (= (walls) (set-index walls true 8 9))
         (= (walls) (set-index walls true 8 10))
         (= (walls) (set-index walls true 8 11))
         (= (walls) (set-index walls true 8 12))
         (= (walls) (set-index walls true 8 13))
         (= (walls) (set-index walls true 8 14))
         (= (walls) (set-index walls true 8 15))
         (= (walls) (set-index walls true 8 16))
         (= (walls) (set-index walls true 8 17))
         (= (walls) (set-index walls true 8 18))
         (= (xloc human) 9)
         (= (yloc human) 5)
         (= (xloc robot) 10)
         (= (yloc robot) 5))
  (:goal (has human gem4))
)