(define (problem virtual-home)
  (:domain virtual-home)
  (:objects fridge1 - fridge
            wine1 juice1 cupcake1 cupcake2 cupcake3 cupcake4 cheese1
            cutleryfork1 cutleryfork2 cutleryfork3 cutleryfork4
            wineglass1 wineglass2 wineglass3 wineglass4
            waterglass1 waterglass2 waterglass3 waterglass4 - item
            table1- table
            robot - robot
            human - human
            cabinet1 cabinet2 cabinet3 cabinet4 cabinet5 - cabinet)
  (:init (active human)
         (next-turn human robot)
         (next-turn robot human)
         (at robot table1)
         (at human table1)
         (in cheese1 fridge1)
         (in cupcake1 fridge1)
         (in cupcake2 fridge1)
         (in cupcake3 fridge1)
         (in cupcake4 fridge1)
         (in juice1 fridge1)
         (in wine1 fridge1)
         (in waterglass1 cabinet3)
         (in waterglass2 cabinet3)
         (in waterglass3 cabinet3)
         (in waterglass4 cabinet3)
         (in wineglass1 cabinet3)
         (in wineglass2 cabinet3)
         (in wineglass3 cabinet3)
         (in wineglass4 cabinet3)
         (in cutleryfork1 cabinet4)
         (in cutleryfork2 cabinet4)
         (in cutleryfork3 cabinet4)
         (in cutleryfork4 cabinet4)
        ;  (isset2 cutleryfork1 cutleryfork2)
        ;  (isset2 cutleryfork2 cutleryfork3)
        ;  (isset2 cutleryfork3 cutleryfork4)
        ;  (isset3 cutleryfork1 cutleryfork2 cutleryfork3)
        ;  (isset3 cutleryfork2 cutleryfork3 cutleryfork4)
        ;  (isset4 cutleryfork1 cutleryfork2 cutleryfork3 cutleryfork4)
        ;  (isset2 cutleryknife1 cutleryknife2)
        ;  (isset2 cutleryknife2 cutleryknife3)
        ;  (isset2 cutleryknife3 cutleryknife4)
        ;  (isset3 cutleryknife1 cutleryknife2 cutleryknife3)
        ;  (isset3 cutleryknife2 cutleryknife3 cutleryknife4)
        ;  (isset4 cutleryknife1 cutleryknife2 cutleryknife3 cutleryknife4)
        ;  (isset2 bowl1 bowl2)
        ;  (isset2 bowl2 bowl3)
        ;  (isset2 bowl3 bowl4)
        ;  (isset3 bowl1 bowl2 bowl3)
        ;  (isset3 bowl2 bowl3 bowl4)
        ;  (isset4 bowl1 bowl2 bowl3 bowl4)         
        ;  (isset2 plate1 plate2)
        ;  (isset2 plate2 plate3)
        ;  (isset2 plate3 plate4)
        ;  (isset3 plate1 plate2 plate3)
        ;  (isset3 plate2 plate3 plate4)
        ;  (isset4 plate1 plate2 plate3 plate4)         
        ;  (isset2 waterglass1 waterglass2)
        ;  (isset2 waterglass2 waterglass3)
        ;  (isset2 waterglass3 waterglass4)
        ;  (isset3 waterglass1 waterglass2 waterglass3)
        ;  (isset3 waterglass2 waterglass3 waterglass4)
        ;  (isset4 waterglass1 waterglass2 waterglass3 waterglass4)
        ;  (isset2 wineglass1 wineglass2)
        ;  (isset2 wineglass2 wineglass3)
        ;  (isset2 wineglass3 wineglass4)
        ;  (isset3 wineglass1 wineglass2 wineglass3)
        ;  (isset3 wineglass2 wineglass3 wineglass4)
        ;  (isset4 wineglass1 wineglass2 wineglass3 wineglass4)
        )
  (:goal (has human wine1))
)