(define (problem virtual-home)
  (:domain virtual-home)
  (:objects fridge1 - fridge
            onion1 tomato1 potato1 potato1 carrot1 chicken1 salmon1 cucumber1 wine1 juice1 cupcake1 cupcake2 cupcake3 cupcake4 cheese1 cuttingboard1 chefknife1 
            cutleryfork1 cutleryfork2 cutleryfork3 cutleryfork4
            cutleryknife1 cutleryknife2 cutleryknife3 cutleryknife4
            bowl1 bowl2 bowl3 bowl4 plate1 plate2 plate3 plate4 
            wineglass1 wineglass2 wineglass3 wineglass4
            waterglass1 waterglass2 waterglass3 waterglass4 - item
            table1 table2 - table
            robot human - agent
            cabinet1 cabinet2 cabinet3 cabinet4 cabinet5 - cabinet)
  (:init (active human)
         (next-turn human robot)
         (next-turn robot human)
         (in onion1 fridge1)
         (in potato1 fridge1)
         (in carrot1 fridge1)
         (in tomato1 fridge1)
         (in cucumber1 fridge1)
         (in cheese1 fridge1)
         (in cupcake1 fridge1)
         (in cupcake2 fridge1)
         (in cupcake3 fridge1)
         (in cupcake4 fridge1)
         (in juice1 fridge1)
         (in potato1 fridge1)
         (in chicken1 fridge1)
         (in salmon1 fridge1)
         (in wine1 fridge1)
         (in bowl1 cabinet1)
         (in bowl2 cabinet1)
         (in bowl3 cabinet1)
         (in bowl4 cabinet1)
         (in plate1 cabinet2)
         (in plate2 cabinet2)
         (in plate3 cabinet2)
         (in plate4 cabinet2)
         (in waterglass1 cabinet3)
         (in waterglass2 cabinet3)
         (in waterglass3 cabinet3)
         (in waterglass4 cabinet3)
         (in wineglass1 cabinet3)
         (in wineglass2 cabinet3)
         (in wineglass3 cabinet3)
         (in wineglass4 cabinet3)
         (in cutleryfork1 cabinet4)
         (in cutleryfork2 cabinet4)
         (in cutleryfork3 cabinet4)
         (in cutleryfork4 cabinet4)
         (in cutleryknife1 cabinet4)
         (in cutleryknife2 cabinet4)
         (in cutleryknife3 cabinet4)
         (in cutleryknife4 cabinet4)
         (in cuttingboard1 cabinet5 )
         (in chefknife1 cabinet5 )
  (:goal (has human wine1))
)