goal_name = ["set_table1","set_table1b", "set_table2","set_table2b","set_table3","set_table3b","set_table4","set_table4b","wine1","wine1p","wine2","win2p","wine3","win3p","wine4","win4p","juice1","juice1p","juice2","juice2p","juice3","juice3p","juice4","juice4p","veggie_salad","chicken_salad","potato_stew","chicken_stew","salmon_stew"]
costs = (
    pickup=1.0, takeout=1.0, putdown=1.0, noop=0.01, goal=0
)


goals = @pddl("(and (on cutleryfork1 table1) (on cutleryknife1 table1) (on plate1 table1))",
"(and (on cutleryfork1 table1)(on cutleryfork2 table1) (on cutleryknife1 table1)(on cutleryknife2 table1) (on plate1 table1)(on plate2 table1))",
"(and (on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryfork3 table1) (on cutleryknife1 table1)(on cutleryknife2 table1)(on cutleryknife3 table1) (on plate1 table1)(on plate2 table1)(on plate3 table1))",
"(and (on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryfork3 table1)(on cutleryfork4 table1) (on cutleryknife1 table1)(on cutleryknife2 table1)(on cutleryknife3 table1)(on cutleryknife4 table1) (on plate1 table1)(on plate2 table1)(on plate3 table1)(on plate4 table1))",
"(and (on cutleryfork1 table1)(on cutleryknife1 table1)(on plate1 table1)(on bowl1 table1))",
"(and (on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryknife1 table1)(on cutleryknife2 table1) (on plate1 table1)(on plate2 table1) (on bowl1 table1)(on bowl2 table1))",
"(and (on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryfork3 table1)(on cutleryknife1 table1)(on cutleryknife2 table1)(on cutleryknife3 table1) (on plate1 table1)(on plate2 table1)(on plate3 table1) (on bowl1 table1)(on bowl2 table1)(on bowl3 table1))",
"(and (on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryfork3 table1)(on cutleryfork4 table1) (on cutleryknife1 table1)(on cutleryknife2 table1)(on cutleryknife3 table1)(on cutleryknife4 table1) (on plate1 table1)(on plate2 table1)(on plate3 table1)(on plate4 table1) (on bowl1 table1)(on bowl2 table1)(on bowl3 table1)(on bowl4 table1))",
"(and (on wineglass1 table1)(on wine1 table1))",
"(and (on wineglass1 table1)(on wineglass2 table1) (on wine1 table1))",
"(and (on wineglass1 table1)(on wineglass2 table1)(on wineglass3 table1) (on wine1 table1))",
"(and (on wineglass1 table1)(on wineglass2 table1)(on wineglass3 table1)(on wineglass4 table1) (on wine1 table1))",
"(and (on wineglass1 table1) (on cutleryfork1 table1)(on wine1 table1)(on cheese1 table1))",
"(and (on wineglass1 table1)(on wineglass2 table1) (on cutleryfork1 table1)(on cutleryfork2 table1)(on wine1 table1)(on cheese1 table1))",
"(and (on wineglass1 table1)(on wineglass2 table1)(on wineglass3 table1) (on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryfork3 table1)(on wine1 table1)(on cheese1 table1))",
"(and (on wineglass1 table1)(on wineglass2 table1)(on wineglass3 table1)(on wineglass4 table1) (on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryfork3 table1)(on cutleryfork4 table1)(on wine1 table1)(on cheese1 table1))",
"(and (on waterglass1 table1)(on juice1 table1))",
"(and (on waterglass1 table1)(on waterglass2 table1)(on juice1 table1))",
"(and (on waterglass1 table1)(on waterglass2 table1)(on waterglass3 table1)(on juice1 table1))",
"(and (on waterglass1 table1)(on waterglass2 table1)(on waterglass3 table1)(on waterglass4 table1)(on juice1 table1))",
"(and (on waterglass1 table1)(on cutleryfork1 table1)(on cupcake1 table1)(on juice1 table1))",
"(and (on waterglass1 table1)(on waterglass2 table1)(on cutleryfork1 table1)(on cutleryfork2 table1)(on cupcake1 table1)(on cupcake2 table1)(on juice1 table1))",
"(and (on waterglass1 table1)(on waterglass2 table1)(on waterglass3 table1)(on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryfork3 table1)(on cupcake1 table1)(on cupcake2 table1)(on cupcake3 table1)(on juice1 table1))",
"(and (on waterglass1 table1)(on waterglass2 table1)(on waterglass3 table1)(on waterglass4 table1)(on cutleryfork1 table1)(on cutleryfork2 table1)(on cutleryfork3 table1)(on cutleryfork4 table1)(on cupcake1 table1)(on cupcake2 table1)(on cupcake3 table1)(on cupcake4 table1)(on juice1 table1))",
"(and (on onion1 table1) (on cucumber1 table1) (on tomato1 table1) (on chefknife1 table1))",
"(and (on onion1 table1) (on cucumber1 table1) (on chicken1 table1) (on chefknife1 table1))",
"(and (on onion1 table1) (on carrot1 table1) (on chicken1 table1) (on wine1 table1))",
"(and (on onion1 table1) (on carrot1 table1) (on salmon1 table1) (on wine1 table1))",
"(and (on onion1 table1) (on carrot1 table1) (on potato1 table1) (on wine1 table1))")


action_dict = Dict(1=>@pddl("(takeout human wine1 fridge1)","(noop robot)", "(takeout human wineglass1 cabinet3)"),
          2=>@pddl("(takeout human plate1 cabinet2)","(noop robot)", "(takeout human plate2 cabinet2)"),
          3=>@pddl("(takeout human plate1 cabinet2)","(noop robot)", "(takeout human plate2 cabinet2)","(noop robot)", "(takeout human plate3 cabinet2)"),
          4=>@pddl("(takeout human plate1 cabinet2)","(noop robot)", "(takeout human plate2 cabinet2)","(noop robot)", "(takeout human bowl1 cabinet1)","(noop robot)","(takeout human bowl2 cabinet1)","(noop robot)"),
          5=>@pddl("(takeout human potato1 fridge1)","(noop robot)", "(takeout human wine1 fridge1)"),
          6=>@pddl("(takeout human juice1 fridge1)","(noop robot)"),
          7=>@pddl("(takeout human plate1 cabinet2)","(noop robot)", "(takeout human plate2 cabinet2)","(noop robot)", "(takeout human cutleryfork1 cabinet4)","(noop robot)","(takeout human cutleryfork2 cabinet4)","(noop robot)"),
          8=>@pddl("(takeout human plate1 cabinet2)","(noop robot)", "(takeout human wine1 fridge1)","(noop robot)", "(takeout human cheese1 fridge1)"),
          9=>@pddl("(takeout human cutleryfork1 cabinet4)","(noop robot)", "(takeout human cutleryfork2 cabinet4)","(noop robot)", "(takeout human cutleryfork3 cabinet4)"),
          10=>@pddl("(takeout human cutleryfork1 cabinet4)","(noop robot)", "(takeout human cutleryfork2 cabinet4)","(noop robot)", "(takeout human cutleryfork3 cabinet4)","(noop robot)","(takeout human cutleryknife1 cabinet4)","(noop robot)", "(takeout human cutleryknife2 cabinet4)","(noop robot)", "(takeout human cutleryknife3 cabinet4)" ),
          11=>@pddl("(takeout human cutleryfork1 cabinet4)","(noop robot)", "(takeout human cutleryfork2 cabinet4)","(noop robot)", "(takeout human cutleryfork3 cabinet4)","(noop robot)","(takeout human cutleryfork4 cabinet4)","(noop robot)", "(takeout human cutleryknife1 cabinet4)","(noop robot)"),
          12=>@pddl("(takeout human tomato1 fridge1)","(noop robot)","(takeout human cucumber1 fridge1)","(takeout human onion1 fridge1)"),
          13=>@pddl("(takeout human chicken1 fridge1)","(noop robot)","(takeout human cucumber1 fridge1)"),
          14=>@pddl("(takeout human wineglass1 cabinet3)","(noop robot)","(takeout human wineglass2 cabinet3)","(noop robot)","(takeout human wineglass3 cabinet3)"),
          15=>@pddl("(takeout human juice1 fridge1)","(noop robot)","(takeout human waterglass1 cabinet3)","(noop robot)"),
          16=>@pddl("(noop human)"),
          17=>@pddl("(noop human)"),
          18=>@pddl("(noop human)"),
          19=>@pddl("(noop human)"),
          20=>@pddl("(noop human)")
)

utterance_dict=Dict(
    1=>"Can you get 2 more glasses?",
    2=>"Can you get more plates and some forks and knives for 4 people?",
    3=>"I've got the plates, can you get the forks and knives?",
    4=>"We need some cutleries.",
    5=>"Can you get the carrot and onion for the stew?",
    6=>"Can you get 3 glasses?",
    7=>"Can you get the bowls?",
    10=>"Can you find 3 forks and some glasses?",
    12=>"I'll get juice, can you get the glasses and some cupcakes for afternoon tea?",
    13=>"Can you bring the plates?",
    14=>"Could you fetch the rest of the knives and some plates?",
    15=>"I need a knife, can you get it?",
    16=>"Could you hand me a knife?",
    19=>"Can you get the bottle from fridge?",
    20=>"We need 3 more glasses, could you get them from the cabinets?",
    8=>"I'll grab 3 plates for dinner, can you help me find the forks and knives?",
    9=>"I'll get the wine, can you bring me 2 glasses? ",
    17=>"We have 3 people for dinner. I'll get the forks and knives, can you get some plates?",
    18=>"Can you get wine and glasses for 3 people?",
    11=>"I will get the vegetables from the fridge, can you get a knife?"
)

utterance_dict_literal=Dict(
    1=>"Can you get 2 more glasses?",
    2=>"Can you get more plates and some forks and knives for 4 people?",
    3=>"Can you get the forks and knives?",
    4=>"We need some cutlery.",
    5=>"Can you get the carrot and onion for the stew?",
    6=>"Can you get 3 glasses?",
    7=>"Can you get the bowls?",
    8=>"Can you help me find the forks and knives?",
    9=>"Can you bring me 2 glasses? ",
    10=>"Can you find 3 forks and some glasses?",
    11=>"Can you get a knife?",
    12=>"Can you get the glasses and some cupcakes for afternoon tea?",
    13=>"Can you bring the plates?",
    14=>"Could you fetch the rest of the knives and some plates?",
    15=>"I need a knife, can you get it?",
    16=>"Could you hand me a knife?",
    17=>"We have 3 people for dinner. Can you get some plates?",
    18=>"Can you get wine and glasses for 3 people?",
    19=>"Can you get the bottle from fridge?",
    20=>"We need 3 more glasses, could you get them from the cabinets?"
)