; Can you help me unlock the blue door there?
(down human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(left human)
(noop robot)
(pickup human key2)
(noop robot)
(right human)
(noop robot)
(right human)
(noop robot)
