(define (problem doors-keys-gems-problem)
  (:domain doors-keys-gems)
  (:objects door1 door2 door3 - door
            key1 key2 - key
            gem1 gem2 gem3 gem4 - gem
            red blue - color
            human robot - agent)
  (:init (= (walls) (new-bit-matrix false 7 7))
         (= (agentcode human) 0)
         (= (agentcode robot) 1)
         (= (turn) 0)
         (= (xloc key1) 1)
         (= (yloc key1) 1)
         (iscolor key1 red)
         (= (xloc key2) 7)
         (= (yloc key2) 1)
         (iscolor key2 blue)
         (= (walls) (set-index walls true 2 1))
         (= (walls) (set-index walls true 2 2))
         (= (walls) (set-index walls true 2 3))
         (= (walls) (set-index walls true 2 5))
         (= (walls) (set-index walls true 2 6))
         (= (walls) (set-index walls true 2 7))
         (= (walls) (set-index walls true 3 1))
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 3))
         (= (walls) (set-index walls true 3 5))
         (= (walls) (set-index walls true 3 6))
         (= (walls) (set-index walls true 3 7))
         (= (xloc gem1) 1)
         (= (yloc gem1) 4)
         (= (xloc door1) 6)
         (= (yloc door1) 4)
         (iscolor door1 red)
         (locked door1)
         (= (xloc gem2) 7)
         (= (yloc gem2) 4)
         (= (walls) (set-index walls true 5 1))
         (= (walls) (set-index walls true 5 2))
         (= (walls) (set-index walls true 5 3))
         (= (walls) (set-index walls true 5 5))
         (= (walls) (set-index walls true 5 6))
         (= (walls) (set-index walls true 5 7))
         (= (walls) (set-index walls true 6 1))
         (= (walls) (set-index walls true 6 2))
         (= (walls) (set-index walls true 6 3))
         (= (walls) (set-index walls true 6 5))
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 7))
         (= (xloc gem3) 1)
         (= (yloc gem3) 7)
         (= (xloc door2) 3)
         (= (yloc door2) 7)
         (iscolor door2 blue)
         (locked door2)
         (= (xloc door3) 6)
         (= (yloc door3) 7)
         (iscolor door3 blue)
         (locked door3)
         (= (xloc gem4) 7)
         (= (yloc gem4) 7)
         (= (xloc human) 3)
         (= (yloc human) 4)
         (= (xloc robot) 4)
         (= (yloc robot) 1))
  (:goal (has human gem3))
)