(define (problem doors-keys-gems-problem)
  (:domain doors-keys-gems)
  (:objects door1 door2 - door
            key1 key2 - key
            gem1 gem2 gem3 gem4 - gem
            red blue - color
            human robot - agent)
  (:init (= (walls) (new-bit-matrix false 8 8))
         (= (agentcode human) 0)
         (= (agentcode robot) 1)
         (= (turn) 0)
         (= (xloc gem1) 8)
         (= (yloc gem1) 1)
         (= (walls) (set-index walls true 2 2))
         (= (walls) (set-index walls true 2 3))
         (= (walls) (set-index walls true 2 4))
         (= (walls) (set-index walls true 2 5))
         (= (walls) (set-index walls true 2 6))
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 3))
         (= (xloc key1) 5)
         (= (yloc key1) 3)
         (iscolor key1 red)
         (= (walls) (set-index walls true 3 6))
         (= (walls) (set-index walls true 3 7))
         (= (xloc door1) 1)
         (= (yloc door1) 4)
         (iscolor door1 red)
         (locked door1)
         (= (walls) (set-index walls true 4 6))
         (= (walls) (set-index walls true 4 7))
         (= (walls) (set-index walls true 5 2))
         (= (walls) (set-index walls true 5 3))
         (= (walls) (set-index walls true 5 4))
         (= (walls) (set-index walls true 5 5))
         (= (walls) (set-index walls true 5 6))
         (= (walls) (set-index walls true 5 7))
         (= (walls) (set-index walls true 6 2))
         (= (walls) (set-index walls true 6 3))
         (= (walls) (set-index walls true 6 4))
         (= (walls) (set-index walls true 6 5))
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 7))
         (= (xloc gem2) 1)
         (= (yloc gem2) 7)
         (= (walls) (set-index walls true 7 2))
         (= (walls) (set-index walls true 7 3))
         (= (walls) (set-index walls true 7 4))
         (= (xloc key2) 7)
         (= (yloc key2) 7)
         (iscolor key2 blue)
         (= (xloc door2) 3)
         (= (yloc door2) 8)
         (iscolor door2 blue)
         (locked door2)
         (= (xloc gem3) 6)
         (= (yloc gem3) 8)
         (= (xloc gem4) 8)
         (= (yloc gem4) 8)
         (= (xloc human) 6)
         (= (yloc human) 1)
         (= (xloc robot) 4)
         (= (yloc robot) 4))
  (:goal (has human gem2))
)