(define (problem doors-keys-gems-problem)
  (:domain doors-keys-gems)
  (:objects door1 door2 - door
            key1 key2 - key
            gem1 gem2 gem3 gem4 - gem
            red blue - color
            human robot - agent)
  (:init (= (walls) (new-bit-matrix false 8 8))
         (= (agentcode human) 0)
         (= (agentcode robot) 1)
         (= (turn) 0)
         (= (xloc gem1) 1)
         (= (yloc gem1) 1)
         (= (xloc gem2) 3)
         (= (yloc gem2) 1)
         (= (walls) (set-index walls true 1 4))
         (= (xloc gem3) 8)
         (= (yloc gem3) 1)
         (= (xloc key1) 1)
         (= (yloc key1) 2)
         (iscolor key1 red)
         (= (xloc key2) 6)
         (= (yloc key2) 2)
         (iscolor key2 blue)
         (= (walls) (set-index walls true 2 7))
         (= (walls) (set-index walls true 2 8))
         (= (xloc door1) 1)
         (= (yloc door1) 3)
         (iscolor door1 red)
         (locked door1)
         (= (walls) (set-index walls true 3 2))
         (= (walls) (set-index walls true 3 3))
         (= (walls) (set-index walls true 3 4))
         (= (xloc door2) 5)
         (= (yloc door2) 3)
         (iscolor door2 blue)
         (locked door2)
         (= (walls) (set-index walls true 3 6))
         (= (walls) (set-index walls true 3 7))
         (= (xloc gem4) 8)
         (= (yloc gem4) 3)
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 7))
         (= (walls) (set-index walls true 5 2))
         (= (walls) (set-index walls true 5 5))
         (= (walls) (set-index walls true 5 7))
         (= (walls) (set-index walls true 6 5))
         (= (walls) (set-index walls true 6 7))
         (= (walls) (set-index walls true 7 1))
         (= (walls) (set-index walls true 7 2))
         (= (walls) (set-index walls true 7 3))
         (= (walls) (set-index walls true 7 5))
         (= (walls) (set-index walls true 7 7))
         (= (walls) (set-index walls true 8 5))
         (= (xloc human) 1)
         (= (yloc human) 8)
         (= (xloc robot) 3)
         (= (yloc robot) 2))
  (:goal (has human gem1))
)