(define (problem doors-keys-gems-problem)
  (:domain doors-keys-gems)
  (:objects door1 door2 door3 door4 door5 door6 door7 - door
            key1 key2 key3 key4 key5 key6 key7 - key
            gem1 gem2 gem3 gem4 - gem
            human robot - agent)
  (:init (= (walls) (new-bit-matrix false 9 10))
         (= (agentcode human) 0)
         (= (agentcode robot) 1)
         (= (turn) 0)
         (= (walls) (set-index walls true 1 1))
         (= (walls) (set-index walls true 1 2))
         (= (walls) (set-index walls true 1 3))
         (= (walls) (set-index walls true 1 4))
         (= (walls) (set-index walls true 1 5))
         (= (walls) (set-index walls true 1 6))
         (= (xloc key1) 8)
         (= (yloc key1) 1)
         (iscolor key1 red)
         (= (xloc key2) 9)
         (= (yloc key2) 1)
         (iscolor key2 blue)
         (= (walls) (set-index walls true 2 1))
         (= (walls) (set-index walls true 2 2))
         (= (walls) (set-index walls true 2 3))
         (= (walls) (set-index walls true 2 4))
         (= (walls) (set-index walls true 2 5))
         (= (walls) (set-index walls true 2 6))
         (= (xloc key3) 7)
         (= (yloc key3) 2)
         (iscolor key3 yellow)
         (= (xloc key4) 10)
         (= (yloc key4) 2)
         (iscolor key4 red)
         (= (xloc gem1) 1)
         (= (yloc gem1) 3)
         (= (walls) (set-index walls true 3 2))
         (= (xloc gem2) 3)
         (= (yloc gem2) 3)
         (= (walls) (set-index walls true 3 4))
         (= (walls) (set-index walls true 3 5))
         (= (walls) (set-index walls true 3 6))
         (= (xloc key5) 7)
         (= (yloc key5) 3)
         (iscolor key5 green)
         (= (xloc key6) 10)
         (= (yloc key6) 3)
         (iscolor key6 blue)
         (= (walls) (set-index walls true 4 2))
         (= (walls) (set-index walls true 4 4))
         (= (walls) (set-index walls true 4 5))
         (= (walls) (set-index walls true 4 6))
         (= (walls) (set-index walls true 4 7))
         (= (walls) (set-index walls true 4 9))
         (= (walls) (set-index walls true 4 10))
         (= (xloc door1) 1)
         (= (yloc door1) 5)
         (iscolor door1 green)
         (locked door1)
         (= (walls) (set-index walls true 5 2))
         (= (xloc door2) 3)
         (= (yloc door2) 5)
         (iscolor door2 red)
         (locked door2)
         (= (walls) (set-index walls true 5 4))
         (= (walls) (set-index walls true 5 5))
         (= (walls) (set-index walls true 5 6))
         (= (walls) (set-index walls true 5 7))
         (= (walls) (set-index walls true 5 9))
         (= (walls) (set-index walls true 5 10))
         (= (xloc door3) 2)
         (= (yloc door3) 6)
         (iscolor door3 red)
         (locked door3)
         (= (xloc key7) 5)
         (= (yloc key7) 6)
         (iscolor key7 blue)
         (= (walls) (set-index walls true 6 6))
         (= (walls) (set-index walls true 6 7))
         (= (walls) (set-index walls true 7 1))
         (= (walls) (set-index walls true 7 2))
         (= (walls) (set-index walls true 7 9))
         (= (walls) (set-index walls true 7 10))
         (= (walls) (set-index walls true 8 1))
         (= (walls) (set-index walls true 8 2))
         (= (xloc door4) 3)
         (= (yloc door4) 8)
         (iscolor door4 red)
         (locked door4)
         (= (walls) (set-index walls true 8 4))
         (= (walls) (set-index walls true 8 5))
         (= (walls) (set-index walls true 8 6))
         (= (walls) (set-index walls true 8 7))
         (= (walls) (set-index walls true 8 8))
         (= (walls) (set-index walls true 8 9))
         (= (walls) (set-index walls true 8 10))
         (= (xloc gem3) 1)
         (= (yloc gem3) 9)
         (= (xloc door5) 2)
         (= (yloc door5) 9)
         (iscolor door5 yellow)
         (locked door5)
         (= (xloc door6) 6)
         (= (yloc door6) 9)
         (iscolor door6 blue)
         (locked door6)
         (= (xloc door7) 9)
         (= (yloc door7) 9)
         (iscolor door7 blue)
         (locked door7)
         (= (xloc gem4) 10)
         (= (yloc gem4) 9)
         (= (xloc human) 3)
         (= (yloc human) 7)
         (= (xloc robot) 8)
         (= (yloc robot) 3))
  (:goal (has human gem3))
)